###################################################
# header_dialogs.py
# This file contains declarations for dialogs
# DO NOT EDIT THIS FILE!
###################################################

speaker_pos         = 0
flags_pos           = 1
start_state_pos     = 2
conditions_pos      = 3
text_pos            = 4
end_state_pos       = 5
consequences_pos    = 6
voice_pos           = 7

anyone              = 0x00000fff
repeat_for_factions = 0x00001000
repeat_for_parties  = 0x00002000
repeat_for_troops   = 0x00003000
repeat_for_100      = 0x00004000
repeat_for_1000     = 0x00005000

plyr                = 0x00010000
party_tpl           = 0x00020000
auto_proceed        = 0x00040000
multi_line          = 0x00080000
other               = 0x00100000

other_bits          = 20
