from header_common import *
from header_operations import *
from header_mission_templates import *
from header_animations import *
from header_sounds import *
from header_music import *
from header_items import *
from module_constants import *

####################################################################################################################
#   Each mission-template is a tuple that contains the following fields:
#  1) Mission-template id (string): used for referencing mission-templates in other files.
#     The prefix mt_ is automatically added before each mission-template id
#
#  2) Mission-template flags (int): See header_mission-templates.py for a list of available flags
#  3) Mission-type(int): Which mission types this mission template matches.
#     For mission-types to be used with the default party-meeting system,
#     this should be 'charge' or 'charge_with_ally' otherwise must be -1.
#
#  4) Mission description text (string).
#  5) List of spawn records (list): Each spawn record is a tuple that contains the following fields:
#    5.1) entry-no: Troops spawned from this spawn record will use this entry
#    5.2) spawn flags.
#    5.3) alter flags. which equipment will be overriden
#    5.4) ai flags.
#    5.5) Number of troops to spawn.
#    5.6) list of equipment to add to troops spawned from here (maximum 8).
#  6) List of triggers (list).
#     See module_triggers.py for infomation about triggers.
#
#  Please note that mission templates is work in progress and can be changed in the future versions.
#
####################################################################################################################

mission_templates = [
  ("conquest", mtf_battle_mode, -1, "Fight for control of the castles.",
   [
    (0,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (1,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (2,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (3,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (4,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (5,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (6,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (7,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (8,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (9,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (10,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (11,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (12,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (13,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (14,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (15,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (16,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (17,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (18,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (19,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (20,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (21,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (22,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (23,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (24,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (25,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (26,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (27,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (28,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (29,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (30,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (31,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (32,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (33,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (34,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (35,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (36,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (37,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (38,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (39,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (40,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (41,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (42,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (43,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (44,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (45,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (46,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (47,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (48,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (49,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (50,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (51,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (52,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (53,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (54,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (55,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (56,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (57,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (58,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (59,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (60,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (61,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (62,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (63,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (64,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (65,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (66,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (67,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (68,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (69,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (70,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (71,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (72,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (73,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (74,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (75,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (76,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (77,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (78,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (79,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (80,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (81,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (82,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (83,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (84,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (85,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (86,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (87,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (88,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (89,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (90,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (91,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (92,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (93,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (94,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (95,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (96,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (97,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (98,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    (99,mtef_visitor_source,0,aif_start_alarmed,1,[]),
    ],
   [
    (ti_before_mission_start, 0, 0, [],
     [(scene_set_day_time, 12),
      (server_set_friendly_fire, 1),
      (server_set_melee_friendly_fire, 1),
      (server_set_friendly_fire_damage_self_ratio, 0),
      (server_set_friendly_fire_damage_friend_ratio, 100),
      (team_set_relation, team_default, team_default, -1),
      (team_set_relation, team_default, team_spawn_invulnerable, 0),
      (team_set_relation, team_spawn_invulnerable, team_default, 0),
      (team_set_relation, team_spawn_invulnerable, team_spawn_invulnerable, 0),
      (team_set_relation, team_spawn_invulnerable, team_faction_1, 0),
      (team_set_relation, team_faction_1, team_spawn_invulnerable, 0),
      (team_set_relation, team_spawn_invulnerable, team_faction_2, 0),
      (team_set_relation, team_faction_2, team_spawn_invulnerable, 0),
      (team_set_relation, team_spawn_invulnerable, team_faction_3, 0),
      (team_set_relation, team_faction_3, team_spawn_invulnerable, 0),
      (team_set_relation, team_spawn_invulnerable, team_faction_4, 0),
      (team_set_relation, team_faction_4, team_spawn_invulnerable, 0),
      (multiplayer_is_server),
      (call_script, "script_setup_owner_faction_for_castles"),
      (call_script, "script_setup_all_linked_scene_props"),
      ]),

    (ti_after_mission_start, 0, 0, [],
     [(set_spawn_effector_scene_prop_kind, 0, -1),
      (set_spawn_effector_scene_prop_kind, 1, -1),
      (assign, "$g_preset_message_display_enabled", 0),
      (multiplayer_is_server),
      (call_script, "script_setup_scene_props_after_mission_start"),
      (init_position, pos1),
      (set_spawn_position, pos1),
      (server_get_max_num_players, "$g_spawn_marker_count"),
      (val_add, "$g_spawn_marker_count", 1),
      (try_for_range, ":unused", 0, "$g_spawn_marker_count"),
        (spawn_scene_prop, "spr_spawn_marker"),
      (try_end),
      ]),

    (ti_server_player_joined, 0, 0, [],
     [(store_trigger_param_1, ":player_id"),
      (call_script, "script_setup_player_joined", ":player_id"),
      ]),

    (ti_on_agent_spawn, 0, 0, [],
     [(store_trigger_param_1, ":agent_id"),
      (call_script, "script_on_agent_spawned", ":agent_id"),
      ]),

    (ti_on_agent_killed_or_wounded, 0, 0, [],
     [(store_trigger_param_1, ":dead_agent_id"),
      (store_trigger_param_2, ":killer_agent_id"),
      (multiplayer_is_server),
      (call_script, "script_setup_agent_for_respawn", ":dead_agent_id"),
      ]),

    (ti_on_agent_mount, 0, 0, [],
     [(store_trigger_param_1, ":agent_id"),
      (store_trigger_param_2, ":horse_agent_id"),
      (agent_set_slot, ":horse_agent_id", slot_agent_horse_last_rider, ":agent_id"),
      ]),

    (ti_on_agent_dismount, 0, 0, [],
     [(store_trigger_param_1, ":agent_id"),
      (store_trigger_param_2, ":horse_agent_id"),
      (agent_set_slot, ":horse_agent_id", slot_agent_horse_last_rider, ":agent_id"),
      ]),

    (0, 0, 0.1,
     [(multiplayer_is_server),
      (val_add, "$g_loop_player_id", 1),
      (get_max_players, ":max_players"),
      (try_begin),
        (ge, "$g_loop_player_id", ":max_players"),
        (assign, "$g_loop_player_id", 0),
        (store_mission_timer_a, ":time"),
        (try_begin),
          (ge, ":time", "$g_loop_player_check_time"),
          (val_add, "$g_loop_player_check_time", loop_player_check_interval),
          (assign, "$g_loop_player_check", 1),
        (else_try),
          (assign, "$g_loop_player_check", 0),
        (try_end),
      (try_end),
      (try_begin),
        (gt, "$g_loop_player_id", 0),
        (assign, ":player_id", "$g_loop_player_id"),
        (try_begin),
          (eq, "$g_loop_player_check", 1),
          (call_script, "script_player_check_stored_values", ":player_id"),
        (try_end),
        (player_is_active, ":player_id"),
        (call_script, "script_player_check_spawn_agent", ":player_id"),
      (try_end),
      (eq, "$g_loop_player_id", 0),
      ], []),

    (0, 0, 30,
     [(multiplayer_is_server),
      (assign, ":agent_id", -1),
      (try_for_agents, ":loop_agent_id"),
        (gt, ":loop_agent_id", "$g_loop_agent_last_checked"),
        (agent_is_active, ":loop_agent_id"),
        (assign, ":agent_id", ":loop_agent_id"),
      (try_end),
      (try_begin),
        (gt, ":agent_id", -1),
        (neg|agent_is_human, ":loop_agent_id"),
        (call_script, "script_check_remove_lost_horse", ":agent_id"),
      (try_end),
      (assign, "$g_loop_agent_last_checked", ":agent_id"),
      (eq, ":agent_id", -1),
      ], []),

    (ti_escape_pressed, 0, 0, [],
     [(finish_mission),
      ]),

    (ti_battle_window_opened, 0, 0, [],
     [(try_begin),
        (eq, "$g_display_agent_labels", 1),
        (start_presentation, "prsnt_display_agent_labels"),
      (try_end),
      ]),

    (0, 0, 0, [(game_key_clicked, gk_character_window)],
     [(try_begin),
        (eq, "$g_display_agent_labels", 0),
        (assign, "$g_display_agent_labels", 1),
        (start_presentation, "prsnt_display_agent_labels"),
      (else_try),
        (assign, "$g_display_agent_labels", 0),
      (try_end),
      ]),

    (0, 1, 1, [(key_clicked, key_slash)],
     [(multiplayer_send_message_to_server, client_event_detach_scene_prop),
      ]),

    (1, 0, ti_once, [(neg|multiplayer_is_server)],
     [(assign, "$g_preset_message_display_enabled", 1),
      ]),

    (0, 0, ti_once, [(neg|multiplayer_is_server)],
     [(call_script, "script_preset_message", "str_pw_welcome", preset_message_read_object, 0, 0),
      ]),

    ]),

  ("edit_scene", 0, -1, "edit_scene", [(0,0,0,0,1,[])],
   [
    (ti_before_mission_start, 0, 0, [],
     [(scene_set_day_time, 12),
      (server_set_add_to_game_servers_list, 0),
      (assign, "$g_edit_scene", 1),
      ]),

    (ti_escape_pressed, 0, 0, [],
     [(question_box, "str_leave_edit_mode"),
      ]),

    (ti_question_answered, 0, 0, [],
     [(store_trigger_param_1, ":answer"),
      (eq, ":answer", 0),
      (finish_mission),
      ]),

    (0, 0, 0, [(key_clicked, key_f12)],
     [(scene_prop_get_instance, ":instance_id", "spr_pw_test_gold", 0),
      (prop_instance_get_position, pos1, ":instance_id"),
      (get_player_agent_no, ":agent_id"),
      (agent_is_alive, ":agent_id"),
      (agent_get_position, pos2, ":agent_id"),
      (get_distance_between_positions, reg1, pos1, pos2),
      (get_sq_distance_between_positions, reg2, pos1, pos2),
      (display_message, "str_distance_reg1_sq_distance_reg2"),
      ]),

    (0, 0, 0, [(key_clicked, key_f11)],
     [(get_player_agent_no, ":agent_id"),
      (agent_is_alive, ":agent_id"),
      (agent_get_position, pos1, ":agent_id"),
      (position_move_x, 50),
      (set_spawn_position, pos1),
      (spawn_horse, "itm_test_horse"),
      ]),

    ]),
]
