CREATE DATABASE pw_player_names;
USE pw_player_names;

CREATE TABLE player_names (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  unique_id INT(7) UNSIGNED NOT NULL,
  name VARCHAR(28) NOT NULL,
  last_used_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  inserted_by_warband_server_id INT(5) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);

CREATE TABLE clans (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(28) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);

CREATE TABLE clan_tags (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  clan_id INT(5) UNSIGNED NOT NULL,
  tag VARCHAR(28) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (tag)
);

CREATE TABLE clan_players (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  clan_id INT(5) UNSIGNED NOT NULL,
  unique_id INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE warband_servers (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  password CHAR(40) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (password)
);
