CREATE DATABASE pw_player_names;
USE pw_player_names;

CREATE TABLE player_names (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  unique_id INT(7) UNSIGNED NOT NULL,
  name VARCHAR(28) NOT NULL,
  last_used_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);
