CREATE DATABASE persistent_world;
USE persistent_world;

CREATE TABLE player_names (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  unique_id INT(8) UNSIGNED NOT NULL,
  name VARCHAR(28) NOT NULL,
  last_used_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  inserted_by_warband_server_id INT(5) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id),
  KEY (unique_id),
  UNIQUE KEY (name)
);

CREATE TABLE clans (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(28) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
);

CREATE TABLE clan_tags (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  clan_id INT(5) UNSIGNED NOT NULL,
  tag VARCHAR(28) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (tag)
);

CREATE TABLE clan_players (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  clan_id INT(5) UNSIGNED NOT NULL,
  unique_id INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (clan_id, unique_id)
);

CREATE TABLE warband_servers (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  password CHAR(40) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (password)
);

CREATE TABLE admin_permissions (
  id INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  unique_id INT(8) UNSIGNED NOT NULL,
  server_id INT(5) UNSIGNED NOT NULL,
  panel BOOLEAN DEFAULT FALSE NOT NULL,
  gold BOOLEAN DEFAULT FALSE NOT NULL,
  kick BOOLEAN DEFAULT FALSE NOT NULL,
  temporary_ban BOOLEAN DEFAULT FALSE NOT NULL,
  permanent_ban BOOLEAN DEFAULT FALSE NOT NULL,
  kill_fade BOOLEAN DEFAULT FALSE NOT NULL,
  freeze BOOLEAN DEFAULT FALSE NOT NULL,
  teleport_self BOOLEAN DEFAULT FALSE NOT NULL,
  admin_items BOOLEAN DEFAULT FALSE NOT NULL,
  heal_self BOOLEAN DEFAULT FALSE NOT NULL,
  godlike_troop BOOLEAN DEFAULT FALSE NOT NULL,
  ships BOOLEAN DEFAULT FALSE NOT NULL,
  announce BOOLEAN DEFAULT FALSE NOT NULL,
  override_poll BOOLEAN DEFAULT FALSE NOT NULL,
  all_items BOOLEAN DEFAULT FALSE NOT NULL,
  mute BOOLEAN DEFAULT FALSE NOT NULL,
  animals BOOLEAN DEFAULT FALSE NOT NULL,
  factions BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (server_id, unique_id)
);

CREATE TABLE sessions (
  id VARCHAR(32) NOT NULL,
  access_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data TEXT,
  PRIMARY KEY (id)
);
